"""The NLDD components auto-generated from its custom-elements manifest.

lotc-nldd ships a registry fragment (packages/lotc-nldd/.../registry.json,
generated by core/src/generators/nldd/generate-nldd.mjs) + one Jinja template
per NLDD-specific web component. They resolve as <c-*> when nldd is active and
map to the matching <nldd-*> element with attribute + event passthrough.
"""

from pathlib import Path

import pytest
from jinja2 import Environment, FileSystemLoader

from lord_of_the_components import setup_components
from lord_of_the_components.extension import ComponentExtension

PKG = Path(__file__).resolve().parent.parent / "src" / "lord_of_the_components"


@pytest.fixture
def render():
    env = Environment(loader=FileSystemLoader([str(PKG / "templates")]), autoescape=True)
    setup_components(env, design_systems=["nldd", "bgnldd"], registry_path=str(PKG / "registry.json"))
    return lambda s: env.from_string(s).render()


@pytest.mark.parametrize(
    "markup,tag",
    [
        ('<c-avatar initials="AS" name="Anne"/>', "nldd-avatar"),
        ("<c-tooltip>hint</c-tooltip>", "nldd-tooltip"),
        ("<c-pagination/>", "nldd-pagination"),
        ("<c-progress-bar/>", "nldd-progress-bar"),
        ("<c-switch/>", "nldd-switch"),
        ("<c-split-button/>", "nldd-split-button"),
        ('<c-avatar initials="X" @click="go()" data-x="1"/>', "nldd-avatar"),
    ],
)
def test_generated_component_maps_to_nldd_element(render, markup, tag):
    html = render(markup)
    assert f"<{tag}" in html
    assert 'data-lotc-component="' in html


def test_generated_avatar_forwards_attributes_and_events(render):
    html = render('<c-avatar initials="AS" size="lg" decorative @click="go()" data-x="1"/>')
    assert 'initials="AS"' in html and 'size="lg"' in html and "decorative" in html
    assert 'onclick="go()"' in html and 'data-x="1"' in html  # passthrough


def test_nldd_fragment_registers_many_components():
    env = Environment(loader=FileSystemLoader([str(PKG / "templates")]), autoescape=True)
    setup_components(env, design_systems=["nldd"], registry_path=str(PKG / "registry.json"))
    reg = env.extensions[ComponentExtension.identifier].registry
    names = set(reg._components)
    # a good chunk of NLDD-specific components are now addressable as c-*
    for name in ("avatar", "tooltip", "pagination", "modal-dialog", "split-button", "stepper", "combo-box"):
        assert name in names, name


def test_generated_component_absent_without_nldd():
    # The fragment is owned by lotc-nldd: without nldd active the component is
    # not even in the registry -> a hard "unknown component" error.
    from lord_of_the_components import ComponentError

    env = Environment(loader=FileSystemLoader([str(PKG / "templates")]), autoescape=True)
    setup_components(env, design_systems=["rvo"], registry_path=str(PKG / "registry.json"))
    with pytest.raises(ComponentError, match="Unknown component"):
        env.from_string("<c-avatar/>").render()
